on: [push, pull_request, create]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-latest-large]
        jdk: [11]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 9
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.jdk }}
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Execute tests
      run: ./gradlew check
    - name: Assemble fat jar
      run: ./gradlew shadowJar
    - name: Upload jars as artifact
      uses: actions/upload-artifact@v3
      with:
        name: software-challenge-gui-${{ github.sha }}-jars
        path: build/*.jar
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: software-challenge-gui-${{ github.sha }}-jars
        path: build
    - name: Release ${{ github.ref }}
      uses: softprops/action-gh-release@v1
      with:
        files: build/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}